# @package _global_
config:
  VERBOSE: False
  LOG_FREQUENCY: 10
  TEST_ONLY: False
  TEST_MODEL: True
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  HOOKS:
    PERF_STATS:
      MONITOR_PERF_STATS: False
      PERF_STAT_FREQUENCY: 40
      ROLLING_BTIME_FREQ: 5
    TENSORBOARD_SETUP:
      USE_TENSORBOARD: True
      EXPERIMENT_LOG_DIR: "linear_decals"
      LOG_PARAMS: False
      LOG_PARAMS_GRADIENTS: False
      FLUSH_EVERY_N_MIN: 1
  DATA:
    NUM_DATALOADER_WORKERS: 32
    DECALS:
      H5KEY_IMG: images
      H5KEY_LAB: specz
      DEREDDENED: True
      FILTERS_USE: &filters_use ['g', 'r', 'z']
    TRAIN:
      DATA_SOURCES: [decals_hdf5]
      DATASET_NAMES: [decals_TH_pretrain_south]
      BATCHSIZE_PER_REPLICA: 256
      TRANSFORMS:
        - name: CenterCropDecals
          outdim: 96
          jitter_lim: 7
        - name: RGBifyDecals
        - name: ToTensor
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
      DROP_LAST: True
    TEST:
      DATA_SOURCES: [decals_hdf5]
      DATASET_NAMES: [decals_TH_pretrain_south]
      BATCHSIZE_PER_REPLICA: 256
      TRANSFORMS:
        - name: CenterCropDecals
          outdim: 96
          jitter_lim: 7
        - name: RGBifyDecals
        - name: ToTensor
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
      DROP_LAST: True
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 1
      topk_values: [1]
  TRAINER:
    TRAIN_STEP_NAME: standard_train_step
  MODEL:
    FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: True
      FREEZE_TRUNK_ONLY: True
      SHOULD_FLATTEN_FEATS: False
    TRUNK:
      NAME: vision_transformer
      VISION_TRANSFORMERS:
        IMAGE_SIZE: 96
        PATCH_SIZE: 16
        NUM_LAYERS: 12
        NUM_HEADS: 6
        HIDDEN_DIM: 384
        MLP_DIM: 1532
        CLASSIFIER: token
        DROPOUT_RATE: 0
        ATTENTION_DROPOUT_RATE: 0
        QKV_BIAS: True
        DROP_PATH_RATE: 0.1 # stochastic depth dropout probability
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 384, "dims": [384, 2]}],
      ]
    AMP_PARAMS:
      AMP_TYPE: pytorch
      USE_AMP: True
  LOSS:
    name: bce_logits_multiple_output_single_target
  OPTIMIZER:
    name: sgd
    weight_decay: 0.
    momentum: 0.9
    num_epochs: 28
    nesterov: False
    regularize_bn: False
    regularize_bias: True
    param_schedulers:
      lr:
        auto_lr_scaling:
          auto_scale: False
        name: cosine 
        start_value: 0.002  # LR for batch size 256
        end_value: 0.0000
        update_interval: epoch
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 8
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
  CHECKPOINT:
    DIR: "."
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 5
    OVERWRITE_EXISTING: true



